image: rust:latest

stages:
  - build
  - img-build
  - coverage

rust-latest:
  stage: build
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose

img-build:
  stage: img-build
  image: rustlang/rust:nightly
  script:
    - cargo build --release
    - ls target/release
  only:
    - master
  artifacts:
    paths:
      - target/release/libowml_parser.rlib

coverage:
  stage: coverage
  script: |
    echo "Installing kcov"
    cargo install cargo-kcov
    echo "Generating coverage reports with kcov"
    for file in target/debug/owens-ml-parser-*; do [ -x "${file}" ] || continue; mkdir -p "target/cov/$(basename $file)"; cargo-kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done
    bash <(curl -s https://codecov.io/bash)
    echo "Uploaded code coverage"
