image: rust:latest

stages:
  - build
  - img-build

rust-latest:
  stage: build
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose

img-build:
  stage: img-build
  image: rustlang/rust:nightly
  script:
    - cargo build --release
    - ls target/release
  only:
    - master
  artifacts:
    paths:
      - target/release/libowens_ml_parser.rlib
