[package]
name = "owens-ml"
version = "0.1.0"
authors = ["scOwez <owez@scalist.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.0.0"
